name = "f5norg"
license = "CC-BY-SA 2.0"
source_repo = "https://github.com/winks/hugo-f5norg"
description = ""
tags = ["blog", "personal"]
features = ["blog", "personal"]

[author]
    name = "Florian Anderiasch"
    email = "fa@art-core.org"
    url = "https://f5n.org"
